// svelte/src/routes/dashboard/+page.svelte
<div class="flex flex-col p-9">
  <h1 class="text-2xl mb-5">Dashboard</h1>

  <p>Some long content here.</p>

  <div class="h-5" />

  <p>
    The sun was shining brightly in the sky, casting warm rays of light all
    around. The birds sang their sweet melodies in the trees, adding to the
    ambiance of the moment. The flowers were blooming in vibrant colors,
    painting the landscape with a symphony of hues. The gentle breeze carried
    the sweet scent of blooming flowers, filling the air with its gentle charm.
    The world was alive and full of beauty, a testament to the magic that
    surrounds us.
  </p>

  <div class="h-5" />

  <p>
    The world was full of wonder, a never-ending source of inspiration. The
    stars twinkled in the night sky, their light guiding the way for the
    curious. The oceans stretched out, vast and deep, home to an array of
    wondrous creatures. The mountains towered above, their peaks reaching for
    the sky, a reminder of the power and majesty of nature. The world was full
    of surprises, a constant source of awe and joy.
  </p>

  <p>
    Life was full of moments that took your breath away, filling you with a
    sense of awe and wonder. The beauty of nature was a constant reminder of the
    incredible complexity and diversity of our world. From the intricate
    patterns on a butterfly's wings to the majesty of a towering mountain range,
    there was always something new to marvel at. And in those moments, you were
    reminded of the magic that lay just beyond the edge of everyday life,
    waiting to be discovered.
  </p>
  <p>
    The world was a tapestry of colors, sounds, and smells, a never-ending
    journey of discovery. The warmth of a crackling fire on a cold winter night,
    the smell of freshly baked bread wafting from a nearby bakery, the sound of
    laughter and conversation filling the air as friends and family gathered
    together. These were the moments that made life worth living, the moments
    that made you grateful for the gift of existence.
  </p>
</div>

// next/src/app/dashboard/page.tsx
export default function Dashboard() {
  return (
    <div className="flex flex-col p-9">
      <h1 className="text-2xl mb-5">Dashboard</h1>

      <p>Some long content here.</p>

      <div className="h-5" />

      <p>
        The sun was shining brightly in the sky, casting warm rays of light all
        around. The birds sang their sweet melodies in the trees, adding to the
        ambiance of the moment. The flowers were blooming in vibrant colors,
        painting the landscape with a symphony of hues. The gentle breeze
        carried the sweet scent of blooming flowers, filling the air with its
        gentle charm. The world was alive and full of beauty, a testament to the
        magic that surrounds us.
      </p>

      <div className="h-5" />

      <p>
        The world was full of wonder, a never-ending source of inspiration. The
        stars twinkled in the night sky, their light guiding the way for the
        curious. The oceans stretched out, vast and deep, home to an array of
        wondrous creatures. The mountains towered above, their peaks reaching
        for the sky, a reminder of the power and majesty of nature. The world
        was full of surprises, a constant source of awe and joy.
      </p>

      <p>
        Life was full of moments that took your breath away, filling you with a
        sense of awe and wonder. The beauty of nature was a constant reminder of
        the incredible complexity and diversity of our world. From the intricate
        patterns on a butterfly's wings to the majesty of a towering mountain
        range, there was always something new to marvel at. And in those
        moments, you were reminded of the magic that lay just beyond the edge of
        everyday life, waiting to be discovered.
      </p>
      <p>
        The world was a tapestry of colors, sounds, and smells, a never-ending
        journey of discovery. The warmth of a crackling fire on a cold winter
        night, the smell of freshly baked bread wafting from a nearby bakery,
        the sound of laughter and conversation filling the air as friends and
        family gathered together. These were the moments that made life worth
        living, the moments that made you grateful for the gift of existence.
      </p>
    </div>
  );
}
